### ISSUE TITLE
Mix-and-match encrypted and non-encrypted files in a secret

### ISSUE THREAD

**Issue by DrPhil** [goabout/kustomize-sopssecretgenerator#13]
It would be nice to be able to use both encrypted and plaintext files in a secret.

We are probably not following kubernetes best practices, but some of our secrets have values that are not so secret. For example, a secret might contain both a cert and the key to the cert. The cert doesn't have to encrypted since it's public, but there's currently no way to express that with the `SopsSecretGenerator`.

To be explicit, what I am looking for is something in this style:
```
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: my-secrets
files:
  - cert.key.pem
plaintextFiles:
  - cert.pem
```

For shorter values it would also be nice to support `literals` like [the standard configmapgenerator](https://kubernetes-sigs.github.io/kustomize/api-reference/kustomization/configmapgenerator/) does.

**Comment by jcassee** [comment]
Sorry for the delay, I was on holiday.

I'm not convinced about doing this in the plugin. Did you know you can merge generated Secrets? See for example:

https://github.com/kubernetes-sigs/kustomize/blob/766500508c99815598cdf1a8899cedbbb7ee8c32/examples/combineConfigs.md

In essence, if you generate two Secrets with the same name and use `behavior: merge`, the keys should merge together.

Does that help?

**Comment by DrPhil** [comment]
> Did you know you can merge generated Secrets?

Yes. I wanted this for convenience, not because it's enabling something otherwise impossible. Basically, I find it a lot easier to reason about resources when there is less patching/merging/double-checking. It might sound like I don't like Kustomize, but I do! :D It's just a lot easier when its features are not needed.

> I'm not convinced about doing this in the plugin.

Absolutely, it's your call! Thanks for your input, feel free to close this issue.

**Comment by jcassee** [comment]
Alright, in that case let's close the issue. I did appreciate the suggestion, by the way.
