### ISSUE TITLE
Unexecutable plugin error on Windows

### ISSUE THREAD

**Issue by gochist** [goabout/kustomize-sopssecretgenerator#14]
I'm getting error like below on Windows git bash and powershell also.

```
Error: accumulating resources: accumulateFile "accumulating resources from '../../base': 'C:\\Users\\****\\****\\kustomize\\base' must resolve to a file", accumulateDirector: "recursed accumulation of path 'C:\\Users\\****\\****\\kustomize\\base': loading generator plugins: unexecutable plugin at: C:\\Users\\****\\.config\\kustomize\\plugin\\goabout.com\\v1beta1\\sopssecretgenerator\\SopsSecretGenerator"
```

According to the community, `kustomize` does not support exec plugin on Windows. 

https://kubernetes.slack.com/archives/C9A5ALABG/p1585924675198200

**Comment by jcassee** [comment]
Thanks for the heads-up! I created an issue on the kustomize project for clarification. I'll have to remove the Windows binary if this is true. You might need to use something like a Linux VM or Docker (?) to use plugins on Windows...

**Comment by jcassee** [comment]
@gochist Could you try the suggestion made here?

https://github.com/kubernetes-sigs/kustomize/issues/2924#issuecomment-686063807

**Comment by gochist** [comment]
@jcassee I tried and added a comment, https://github.com/kubernetes-sigs/kustomize/issues/2924#issuecomment-692707582.

**Comment by jcassee** [comment]
Silly question, but does is the path to the plugin `C:\\Users\\****\\.config\\kustomize\\plugin\\goabout.com\\v1beta1\\sopssecretgenerator\\SopsSecretGenerator`? I.e. can you try your Go test code on that path instead of your Downloads folder?

**Comment by gochist** [comment]
Not silly at all. I did it with a string, `"C:\\Users\\june.yi\\AppData\\Local\\kustomize\\plugin\\goabout.com\\v1beta1\\sopssecretgenerator\\SopsSecretGenerator.exe"`. And the result is same.

**Comment by jcassee** [comment]
Alright, so it seems the problem is with exec plugins in general. Let's see what happens in kubernetes-sigs/kustomize#2924. In the mean time I will add a note to the readme.

**Comment by jcassee** [comment]
@gochist  I see you fixed exec plugins on Windows yourself: kubernetes-sigs/kustomize#3027 :sunglasses: 

I think we can close this issue then? Or do the docs require updating?

**Comment by gochist** [comment]
@jcassee Thank you! I'm closing this issue. 👍🏼
