### ISSUE TITLE
Version Output

### ISSUE THREAD

**Issue by mleklund** [goabout/kustomize-sopssecretgenerator#15]
I know it is nitpicky, but would love to be able to print the version of the plugin.  I am not sure if version output is allowed in the interface for exec plugins.

**Comment by jcassee** [comment]
I guess an option to do so would be fine. Do you think you could do the change yourself?

**Comment by mleklund** [comment]
I'll try to take a crack at it.  Haven't written much go.

**Comment by jcassee** [comment]
Great, go for it!

**Comment by mleklund** [comment]
I am going to close for now, as I do not have time to work on it.  I hope to open a MR after we get through the holiday season.

**Comment by jcassee** [comment]
No problem!
