### ISSUE TITLE
Don't understand "use key=file." in the docs

### ISSUE THREAD

**Issue by mabushey** [goabout/kustomize-sopssecretgenerator#16]
First off thanks for this. :) I tied using a different one previously and discovered how defective Go plugins are. When I read "not tied to the specific compilation of Kustomize, like Go plugins are." I was sold.

All seems to be working, except I would like to change the key name to be different than the filename (I like to use .enc for encrypted files)  so I need to change `sshPrivateKey.enc` to `sshPrivateKey`.

According to the docs on https://github.com/goabout/kustomize-sopssecretgenerator:
`If the data is a file and the Secret data key needs to be different from the filename, you can use key=file.`

This is exactly what I want, but what does `key=file` mean? I'm using yaml (not Toml) for kubernetes/kustomize, and using `key: sshPrivateKey` did not work.

The example immediately below this says it shows all options, but there is no reference to `key` anywhere in it.

**Comment by mabushey** [comment]
Figured it out, it was in the "all options" example. I needed:
```
files:
  - sshPrivateKey=sshPrivateKey.enc
```

Maybe change the docs from `you can use key=file` to `you can specify the key by adding `key=filename` instead of just the filename under `files: `.

**Comment by jcassee** [comment]
Hi @mabushey, happy to hear this plugin is useful to you.

I struggled with the wording when I wrote that, because formally the filename as it appears in the Secret is just the key of a key-value pair and only becomes a filename if you mount the Secret in a Pod. I think your suggestion is a good one. I'll update the docs.

**Comment by mabushey** [comment]
It's not easy to explain this. It's almost to simple. Would you like me to create a PR using an example of the ssh key config in ArgoCD? It would add a little bit to the length of the docs but as you have pretty good support for ArgoCD (Thank you @jcassee and @LelandSindt ) I think it would be pretty relevant both as an example and as ArgoCD implementation. Obviously you have to like the PR, but I think I could make it more clear than my text above.

**Comment by jcassee** [comment]
Sure! @LelandSindt wrote [a separate page for ArgoCD](https://github.com/goabout/kustomize-sopssecretgenerator/blob/master/docs/argocd.md). Could that be the place for that?

Anyway, I would love a PR to improve the documentation.

**Comment by jcassee** [comment]
I applied your suggestion in c6840a368859eb8abebed89ef70a538a5f53f1c0. Thanks @mabushey.

I'm closing this issue now. If you have ideas or PRs for further improvement, that would be very welcome.
