### ISSUE TITLE
How to use PGP keys in ArgoCD version?

### ISSUE THREAD

**Issue by rasouza** [goabout/kustomize-sopssecretgenerator#18]
Hello,

probably a very noob question: In the ArgoCD example, there's only examples when you're using GCP or AWS as your KMS. But what if I chose to go with PGP keys for encryption how do I configure my ArgoCD for that?

**Comment by rasouza** [comment]
Just for clarification, I tried to import to ArgoCD my public gpg key in ArgoCD UI under Settings -> GnuPG Keys -> Add Keys. It imported successfully with Key ID `A1924D586049F75E`. Although in `argocd-repo-server` logs I'm getting the following log:

```
argocd-repo-server time="2020-11-13T04:05:10Z" level=error msg="`kustomize build /tmp/https:__github.com_rasouza_diary-infra/diary/users --enable_alpha_plugins` failed exit status 1: Error: env source \"secrets/db.env\": sops could not decrypt: Error getting data key: 0 successful groups required, got 0\nFailed to get the data key required to decrypt the SOPS file.\n\nGroup 0: FAILED\n  A893A7CE422E149B3CCC8A49A1924D586049F75E: FAILED\n    - | could not decrypt data key with PGP key:\n      | golang.org/x/crypto/openpgp error: Could not load secring:\n      | open /home/argocd/.gnupg/secring.gpg: no such file or\n      | directory; GPG binary error: exit status 2\n\nRecovery failed because no master key was able to decrypt the file. In\norder for SOPS to recover the file, at least one key has to be successful,\nbut none were.\nError: failure in plugin configured via /tmp/kust-plugin-config-975633840; exit status 2: exit status 2" execID=XE6Ne
```

I noticed that `A1924D586049F75E` is partially included in the full `A893A7CE422E149B3CCC8A49A1924D586049F75E`. Am I importing it wrong or something?

Thanks

**Comment by jcassee** [comment]
Hi @rasouza, you are correct in thinking that A893A7CE422E149B3CCC8A49A1924D586049F75E is the same key as A1924D586049F75E. Abbreviating PGP/GPG keys is done from the tail end.

Anyway, I don't use ArgoCD myself, so I cannot say how this is supposed to work. In general, I'm not sure a GPG secret key you add through the ArgoCD web interface is automatically exposed to an initContainer. You probably need to do some work for that.

**Comment by rasouza** [comment]
Thanks for the heads up! I'll figure this out and will surely increment your doc

**Comment by mabushey** [comment]
Sops encodes the algo used to encrypt, so it knows if it needs a PGP or KMS key to decode. I believe you would just have to figure out how to install and import the GPG key in the argoCD container.

**Comment by mabushey** [comment]
If you are able to add a GPG key via the web interface, you will find ArgoCD created a secret or CRD for it. The ArgoCD integration into K8s is awesome. You should be able to just dump out the secret created via the GUI and apply it via kubectl.

**Comment by DWSR** [comment]
@mabushey Those are only for verifying the commits that Argo pulls in from repositories.

**Comment by DWSR** [comment]
Got this to work last night: https://gist.github.com/DWSR/e28380fca09398df0fceb65b82b7776c

**Comment by mabushey** [comment]
@rasouza If you have any specific problems, please post them and I will do my best to get you through them. Both ArgoCD and this sops plugin are aweome.

**Comment by jcassee** [comment]
I'm closing this issue. If there is anything more to add, feel free to reopen.
