### ISSUE TITLE
Publish aarch64 binaries

### ISSUE THREAD

**Issue by DWSR** [goabout/kustomize-sopssecretgenerator#20]
For running on top of Raspberry Pis or AWS Graviton instances

**Comment by jcassee** [comment]
Good idea! Do you have a suggestion for the change in [.goreleaser.yml](https://github.com/goabout/kustomize-sopssecretgenerator/blob/c54e51c35df59e115b34070d87c8f5bffa3a4d08/.goreleaser.yml)?

**Comment by devstein** [comment]
@jcassee @DWSR We recently added multi-build support to [KSOPS](https://github.com/viaduct-ai/kustomize-sops/pull/102). Feel free to use it as a reference

**Comment by jcassee** [comment]
@devstein I don't see anything in KSOPS's goreleaser configuration that is different from what we do here, especially regarding aarch64. Could you explain a bit more?

**Comment by jcassee** [comment]
So I guess this is a matter of adding `arm64` to `goarch`.

@DWSR What operating systems make sense for aarch64? Just Linux?

**Comment by DWSR** [comment]
> So I guess this is a matter of adding `arm64` to `goarch`.
For now, yes. It would also make sense to publish container images containing the binaries for easy distribution to clusters, but that's a separate issue.

> @DWSR What operating systems make sense for aarch64? Just Linux?

I'm not sure how M1 Macs are handled by Go, but I think both Linux and Darwin make sense.

**Comment by jcassee** [comment]
Version 1.4.0 (just released) should have built the correct binaries.
