### ISSUE TITLE
configmapgenerator support

### ISSUE THREAD

**Issue by EHSchmitt4395** [goabout/kustomize-sopssecretgenerator#26]
Hello ! Any possibility or hidden support for configmapgenerators and encrypted files?  

Thanks!

**Comment by jcassee** [comment]
Hi @EHSchmitt4395, sorry I didn't answer your message earlier. As ConfigMaps are not designed for sensitive information, I'm not inclined to support it. I think [kustomize-sops](https://github.com/viaduct-ai/kustomize-sops) can encrypt any resource, but I'm not sure.

I'm closing this issue, as it's been a while. However, if you want to continue the discussion, feel free to reopen.

**Comment by devstein** [comment]
Hi @EHSchmitt4395, like @jcassee recommended, [kustomize-sops](https://github.com/viaduct-ai/kustomize-sops) is designed for encrypted K8s resources (ConfigMaps, Secrets, etc)
