### ISSUE TITLE
Kustomize Exec-Plugin deprecated

### ISSUE THREAD

**Issue by flickerfly** [goabout/kustomize-sopssecretgenerator#30]
As was pointed over at kustomize-sops: https://github.com/viaduct-ai/kustomize-sops/issues/141

The Exec-Plugin for Kustomize is slated for deprecation:

https://kubectl.docs.kubernetes.io/guides/extending_kustomize/exec_plugins/

**Comment by shay-berman** [comment]
When this plugin will be migrated to the new kustomize plugin that is not depracated?

**Comment by jcassee** [comment]
That's a good question. Although it should not be that hard, I haven't had time for it myself. If you want, I'd love to help you take a stab at it.
