### ISSUE TITLE
How to replace existing sops secret? 

### ISSUE THREAD

**Issue by shay-berman** [goabout/kustomize-sopssecretgenerator#31]
Hello

I have in the base a sops secret (SopsSecretGenerator) but i want to replace it in the overlay. How i can do it?
There is no clear documentation how to do replace secret using this plugin SopsSecretGenerator.

Thanks

**Comment by jcassee** [comment]
Kustomize is not really designed to remove stuff. You can easily merge more values into a SopsSecretGenerator using `behavior: merge`. (The example in the readme uses `behavior: create`, just change the value.)

**Comment by shay-berman** [comment]
Thanks @jcassee , working well

Consider to mention it in the README file.
