### ISSUE TITLE
[Question] What is `type: Oblique`?

### ISSUE THREAD

**Issue by jskrzypek** [goabout/kustomize-sopssecretgenerator#34]
In the readme, [one of the examples](https://github.com/goabout/kustomize-sopssecretgenerator/blob/master/README.md?plain=1#L107) uses `type: Oblique`. I can find `type: Opaque` in [the K8s docs on Secrets](https://kubernetes.io/docs/concepts/configuration/secret/#opaque-secrets), but the only real Google search result for `Oblique` type secrets is this repo.

What does this mean?

**Comment by jcassee** [comment]
I'm afraid you just found a typo. 🙂

**Comment by jcassee** [comment]
Fixed in 36b9032ccebaed3a6d0cdd5b0c2be3b9957b37b9. Thanks, @jskrzypek!
