### ISSUE TITLE
Not an Issue -- ArgoCD + goabout/kustomize-sopssecretgenerator

### ISSUE THREAD

**Issue by LelandSindt** [goabout/kustomize-sopssecretgenerator#6]
I have been working to setup ArgoCD to deploy kustomize[d] manifests within k3s. I was able to use some patterns from [ksops](https://github.com/viaduct-ai/kustomize-sops#ksops-repo-sever-patch) to use an init container to copy SopsSecretGenerator into the ArgoCD container. 

Would you be interested in pull requests to document this pattern... and would you be interested in publishing the init image required?

[ArgoCD Patch](https://github.com/LelandSindt/argocd/blob/master/patch.yaml)

[Init Image](https://github.com/LelandSindt/kustomize-sopssecretgenerator-init-image)

**Comment by jcassee** [comment]
Hi Leland, I think documenting integration with ArgoCD is useful. I would gladly accept a pull request.

I wonder if a custom Docker image is really required. Why not simply download the plugin from GitHub [as the ArgoCD documentation suggests](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/#adding-tools-via-volume-mounts)?

(By the way, the encrypted file in your repository is named sops.enc.json.txt. Any reason why you did not use sops.enc.json? Did you want to avoid leaving the keys unencrypted?)

**Comment by LelandSindt** [comment]
"Why not simply download the plugin from GitHub...?" --- I had tried that first, and it failed... in ways that I suddenly can't produce...  ¯\_(ツ)_/¯ -- [its working now](https://github.com/LelandSindt/argocd/blob/master/patch.yaml#L23).

sops.enc.json.txt... I wanted sops to encrypt the entire contents of the file so that it would end up in the k8s secret as a single string rather than a series of keys:values... I have yet to go back and test it allowing sops to encrypt it as json... that and, if the file ever changes it will likely be the result of downloading a new <user>.json file from GCP. In this case I don't see a lot of value to retaining the json structure.

**Comment by LelandSindt** [comment]
Any suggestions/requests before I issue the PR?

https://github.com/LelandSindt/kustomize-sopssecretgenerator/commit/7b7a68fce31d4593fd8f8af77aeaff2f55b7f742

**Comment by jcassee** [comment]
>> "Why not simply download the plugin from GitHub...?"
> I had tried that first, and it failed... in ways that I suddenly can't reproduce... ¯\(ツ)/¯ -- its working now.

Maybe it's the use of Wget. Sometimes in the past I was unable to download using Wget, while Curl worked. I think I traced it to robots.txt, but I don't recall exactly. (Hence the use of Curl in the readme example.) Anyway, good to hear it now works. :slightly_smiling_face: 

> In this case I don't see a lot of value to retaining the json structure.

The usual reason for using sops JSON or YAML handling is to see individual value changes in diffs.

> Any suggestions/requests before I issue the PR?

I'll comment inline.

**Comment by LelandSindt** [comment]
https://github.com/goabout/kustomize-sopssecretgenerator/pull/7
