### ISSUE TITLE
Fork exec error

### ISSUE THREAD

**Issue by xakraz** [goabout/kustomize-sopssecretgenerator#8]
Hi,

I am facing the following issue while trying to use your plugin:

```
$ kustomize build --enable_alpha_plugins deployment/overlays/staging

Error: failure in plugin configured via /tmp/kust-plugin-config-568682025; fork/exec /home/USER/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator: exec format error: fork/exec /home/USER/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator: exec format error
```

My `generator.yaml` looks like

```
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: my-secret
envs:
  - config/secrets.enc.env
```

My `kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
...
generators:
  - secretGenerator.yaml
```

Using:
* `kustomize`: `3.5.5`
* `sops`: `v3.5.0`

**Comment by xakraz** [comment]
PEBCAK issue :sweat_smile: 

While copy/pasting the install instruction I have got a html file rather than the binary one ...

Solved

**Comment by jcassee** [comment]
Still, the installation instructions could be wrong. What command got an HTML page?

**Comment by xakraz** [comment]
It seems that my shell (zsh) has escaped the `{` , so the URL was wrong ...
